# Select "HTTP FILE DL" - "P10 Data Rate"
# Select "Type" - "Feature"
# Remove "Family" - "Throughput"
# Remove from "Units" the following "Date", "Time", "DateTime", "IP Address", "Label". "Boolean", "List", "LAT" and "LON"
# Remove "Quality" - "Beta"
# Remove featues related with IdleTime and DelaDelay
# Remove Carrier.Aggregation features
# Remove Test.Throughput.kbit.s"

attributes = ["Session.Duration.s",
              "End.RSSI.dBm",
              "End.RSRP.dBm",
              "End.SINR.dB",
              "End.RSCP.dBm",
              "End.EcNo.dB",
              "Start.RSSI.dBm",
              "Start.RSRP.dBm",
              "Start.SINR.dB",
              "Start.RSCP.dBm",
              "Start.EcNo.dB",
              "Time.to.First.Byte.s",
              "Service.Access.RSSI.Start.dBm",
              "Service.Access.RSRP.Start.dBm",
              "Service.Access.SINR.Start.dB",
              "Service.Access.RSCP.Start.dBm",
              "Service.Access.EcNo.Start.dBm",
              #    "Carrier.Aggregation.SCC1.Usage.%",
              #    "Carrier.Aggregation.SCC2.Usage.%",
              #    "Carrier.Aggregation.SCC3.Usage.%",
              #    "Carrier.Aggregation.SCC4.Usage.%",
              #    "Carrier.Aggregation.SCC1.Usage.%.UL",
              #    "Carrier.Aggregation.SCC2.Usage.%.UL",
              "tcp.frame.time_relative.syn",
              "tcp.frame.time_relative.sck",
              "tcp.first.rtt",
              "tcp.frame.time_relative.ack",
              "tcp.3whs",
              "tcp.frame.time_relative.req",
              "tcp.idle",
              "tcp.frame.time_relative.res",
              "tcp.resp.time",
              "tcp.first.sec.num.ue.ip",
              "tcp.first.sec.num.ports",
              "tcp.first.sec.volume.ul",
              "tcp.first.sec.volume.dl",
              "transfer.frame.time_relative.FirstSec",
              "tcp.first.sec.num.server.ip",
              "tcp.resp_3whs_delta",
              "Abs_DownlinkDelay_min",
              "Abs_DownlinkDelay_25.",
              "Abs_DownlinkDelay_50.",
              "Abs_DownlinkDelay_avg",
              "Abs_DownlinkDelay_75.",
              "Abs_DownlinkDelay_max",
              "Abs_DownlinkDelay_FirstMB",
              "Abs_DownlinkDelay_FirstSec",
              "Abs_DownlinkDelay_VolStep_30KB",
              "Abs_DownlinkDelay_VolStep_90KB",
              "Abs_DownlinkDelay_VolStep_240KB",
              "Abs_DownlinkDelay_VolStep_630KB",
              "Abs_DownlinkDelay_VolStep_1650KB",
              "Abs_DownlinkDelay_VolStep_4320KB",
              "Abs_DownlinkDelay_TimeStep_40ms",
              "Abs_DownlinkDelay_TimeStep_80ms",
              "Abs_DownlinkDelay_TimeStep_160ms",
              "Abs_DownlinkDelay_TimeStep_320ms",
              "Abs_DownlinkDelay_TimeStep_640ms",
              "Abs_DownlinkDelay_TimeStep_1280ms",
              "Abs_DownlinkDelay_TimeStep_2560ms",
              "Abs_DownlinkDelay_TimeStep_5120ms",
              "Abs_DownlinkDelay_TimeStep_10240ms",
              "Abs_DownlinkDelay_TimeStep_20480ms",
              "Abs_UplinkDelay_min",
              "Abs_UplinkDelay_25.",
              "Abs_UplinkDelay_50.",
              "Abs_UplinkDelay_avg",
              "Abs_UplinkDelay_75.",
              "Abs_UplinkDelay_max",
              "Abs_UplinkDelay_FirstMB",
              "Abs_UplinkDelay_FirstSec",
              "Abs_UplinkDelay_VolStep_30KB",
              "Abs_UplinkDelay_VolStep_90KB",
              "Abs_UplinkDelay_VolStep_240KB",
              "Abs_UplinkDelay_VolStep_630KB",
              "Abs_UplinkDelay_VolStep_1650KB",
              "Abs_UplinkDelay_VolStep_4320KB",
              "Abs_UplinkDelay_TimeStep_40ms",
              "Abs_UplinkDelay_TimeStep_80ms",
              "Abs_UplinkDelay_TimeStep_160ms",
              "Abs_UplinkDelay_TimeStep_320ms",
              "Abs_UplinkDelay_TimeStep_640ms",
              "Abs_UplinkDelay_TimeStep_1280ms",
              "Abs_UplinkDelay_TimeStep_2560ms",
              "Abs_UplinkDelay_TimeStep_5120ms",
              "Abs_UplinkDelay_TimeStep_10240ms",
              "Abs_UplinkDelay_TimeStep_20480ms",
              # "Abs_DownlinkDeltaDelay_min",
              # "Abs_DownlinkDeltaDelay_25.",
              # "Abs_DownlinkDeltaDelay_50.",
              # "Abs_DownlinkDeltaDelay_avg",
              # "Abs_DownlinkDeltaDelay_75.",
              # "Abs_DownlinkDeltaDelay_max",
              # "Abs_DownlinkDeltaDelay_FirstMB",
              # "Abs_DownlinkDeltaDelay_FirstSec",
              # "Abs_DownlinkDeltaDelay_VolStep_30KB",
              # "Abs_DownlinkDeltaDelay_VolStep_90KB",
              # "Abs_DownlinkDeltaDelay_VolStep_240KB",
              # "Abs_DownlinkDeltaDelay_VolStep_630KB",
              # "Abs_DownlinkDeltaDelay_VolStep_1650KB",
              # "Abs_DownlinkDeltaDelay_VolStep_4320KB",
              # "Abs_DownlinkDeltaDelay_TimeStep_40ms",
              # "Abs_DownlinkDeltaDelay_TimeStep_80ms",
              # "Abs_DownlinkDeltaDelay_TimeStep_160ms",
              # "Abs_DownlinkDeltaDelay_TimeStep_320ms",
              # "Abs_DownlinkDeltaDelay_TimeStep_640ms",
              # "Abs_DownlinkDeltaDelay_TimeStep_1280ms",
              # "Abs_DownlinkDeltaDelay_TimeStep_2560ms",
              # "Abs_DownlinkDeltaDelay_TimeStep_5120ms",
              # "Abs_DownlinkDeltaDelay_TimeStep_10240ms",
              # "Abs_DownlinkDeltaDelay_TimeStep_20480ms",
              # "Abs_UplinkDeltaDelay_min",
              # "Abs_UplinkDeltaDelay_25.",
              # "Abs_UplinkDeltaDelay_50.",
              # "Abs_UplinkDeltaDelay_avg",
              # "Abs_UplinkDeltaDelay_75.",
              # "Abs_UplinkDeltaDelay_max",
              # "Abs_UplinkDeltaDelay_FirstMB",
              # "Abs_UplinkDeltaDelay_FirstSec",
              # "Abs_UplinkDeltaDelay_VolStep_30KB",
              # "Abs_UplinkDeltaDelay_VolStep_90KB",
              # "Abs_UplinkDeltaDelay_VolStep_240KB",
              # "Abs_UplinkDeltaDelay_VolStep_630KB",
              # "Abs_UplinkDeltaDelay_VolStep_1650KB",
              # "Abs_UplinkDeltaDelay_VolStep_4320KB",
              # "Abs_UplinkDeltaDelay_TimeStep_40ms",
              # "Abs_UplinkDeltaDelay_TimeStep_80ms",
              # "Abs_UplinkDeltaDelay_TimeStep_160ms",
              # "Abs_UplinkDeltaDelay_TimeStep_320ms",
              # "Abs_UplinkDeltaDelay_TimeStep_640ms",
              # "Abs_UplinkDeltaDelay_TimeStep_1280ms",
              # "Abs_UplinkDeltaDelay_TimeStep_2560ms",
              # "Abs_UplinkDeltaDelay_TimeStep_5120ms",
              # "Abs_UplinkDeltaDelay_TimeStep_10240ms",
              # "Abs_UplinkDeltaDelay_TimeStep_20480ms",
              "Abs_RTT_min",
              "Abs_RTT_25.",
              "Abs_RTT_50.",
              "Abs_RTT_avg",
              "Abs_RTT_75.",
              "Abs_RTT_max",
              "Abs_RTT_FirstMB",
              "Abs_RTT_FirstSec",
              "Abs_RTT_VolStep_30KB",
              "Abs_RTT_VolStep_90KB",
              "Abs_RTT_VolStep_240KB",
              "Abs_RTT_VolStep_630KB",
              "Abs_RTT_VolStep_1650KB",
              "Abs_RTT_VolStep_4320KB",
              "Abs_RTT_TimeStep_40ms",
              "Abs_RTT_TimeStep_80ms",
              "Abs_RTT_TimeStep_160ms",
              "Abs_RTT_TimeStep_320ms",
              "Abs_RTT_TimeStep_640ms",
              "Abs_RTT_TimeStep_1280ms",
              "Abs_RTT_TimeStep_2560ms",
              "Abs_RTT_TimeStep_5120ms",
              "Abs_RTT_TimeStep_10240ms",
              "Abs_RTT_TimeStep_20480ms",
              "Abs_CWIN_min",
              "Abs_CWIN_25.",
              "Abs_CWIN_50.",
              "Abs_CWIN_avg",
              "Abs_CWIN_75.",
              "Abs_CWIN_max",
              "Abs_CWIN_FirstMB",
              "Abs_CWIN_FirstSec",
              "Abs_CWIN_VolStep_30KB",
              "Abs_CWIN_VolStep_90KB",
              "Abs_CWIN_VolStep_240KB",
              "Abs_CWIN_VolStep_630KB",
              "Abs_CWIN_VolStep_1650KB",
              "Abs_CWIN_VolStep_4320KB",
              "Abs_CWIN_TimeStep_40ms",
              "Abs_CWIN_TimeStep_80ms",
              "Abs_CWIN_TimeStep_160ms",
              "Abs_CWIN_TimeStep_320ms",
              "Abs_CWIN_TimeStep_640ms",
              "Abs_CWIN_TimeStep_1280ms",
              "Abs_CWIN_TimeStep_2560ms",
              "Abs_CWIN_TimeStep_5120ms",
              "Abs_CWIN_TimeStep_10240ms",
              "Abs_CWIN_TimeStep_20480ms",
              "Abs_RWIN_min",
              "Abs_RWIN_25.",
              "Abs_RWIN_50.",
              "Abs_RWIN_avg",
              "Abs_RWIN_75.",
              "Abs_RWIN_max",
              "Abs_RWIN_FirstMB",
              "Abs_RWIN_FirstSec",
              "Abs_RWIN_VolStep_30KB",
              "Abs_RWIN_VolStep_90KB",
              "Abs_RWIN_VolStep_240KB",
              "Abs_RWIN_VolStep_630KB",
              "Abs_RWIN_VolStep_1650KB",
              "Abs_RWIN_VolStep_4320KB",
              "Abs_RWIN_TimeStep_40ms",
              "Abs_RWIN_TimeStep_80ms",
              "Abs_RWIN_TimeStep_160ms",
              "Abs_RWIN_TimeStep_320ms",
              "Abs_RWIN_TimeStep_640ms",
              "Abs_RWIN_TimeStep_1280ms",
              "Abs_RWIN_TimeStep_2560ms",
              "Abs_RWIN_TimeStep_5120ms",
              "Abs_RWIN_TimeStep_10240ms",
              "Abs_RWIN_TimeStep_20480ms",
              "Abs_WINRatio_min",
              "Abs_WINRatio_25.",
              "Abs_WINRatio_50.",
              "Abs_WINRatio_avg",
              "Abs_WINRatio_75.",
              "Abs_WINRatio_max",
              "Abs_WINRatio_FirstMB",
              "Abs_WINRatio_FirstSec",
              "Abs_WINRatio_VolStep_30KB",
              "Abs_WINRatio_VolStep_90KB",
              "Abs_WINRatio_VolStep_240KB",
              "Abs_WINRatio_VolStep_630KB",
              "Abs_WINRatio_VolStep_1650KB",
              "Abs_WINRatio_VolStep_4320KB",
              "Abs_WINRatio_TimeStep_40ms",
              "Abs_WINRatio_TimeStep_80ms",
              "Abs_WINRatio_TimeStep_160ms",
              "Abs_WINRatio_TimeStep_320ms",
              "Abs_WINRatio_TimeStep_640ms",
              "Abs_WINRatio_TimeStep_1280ms",
              "Abs_WINRatio_TimeStep_2560ms",
              "Abs_WINRatio_TimeStep_5120ms",
              "Abs_WINRatio_TimeStep_10240ms",
              "Abs_WINRatio_TimeStep_20480ms",
              "Abs_RadioBuffer_min",
              "Abs_RadioBuffer_25.",
              "Abs_RadioBuffer_50.",
              "Abs_RadioBuffer_avg",
              "Abs_RadioBuffer_75.",
              "Abs_RadioBuffer_max",
              "Abs_RadioBuffer_FirstMB",
              "Abs_RadioBuffer_FirstSec",
              "Abs_RadioBuffer_VolStep_30KB",
              "Abs_RadioBuffer_VolStep_90KB",
              "Abs_RadioBuffer_VolStep_240KB",
              "Abs_RadioBuffer_VolStep_630KB",
              "Abs_RadioBuffer_VolStep_1650KB",
              "Abs_RadioBuffer_VolStep_4320KB",
              "Abs_RadioBuffer_TimeStep_40ms",
              "Abs_RadioBuffer_TimeStep_80ms",
              "Abs_RadioBuffer_TimeStep_160ms",
              "Abs_RadioBuffer_TimeStep_320ms",
              "Abs_RadioBuffer_TimeStep_640ms",
              "Abs_RadioBuffer_TimeStep_1280ms",
              "Abs_RadioBuffer_TimeStep_2560ms",
              "Abs_RadioBuffer_TimeStep_5120ms",
              "Abs_RadioBuffer_TimeStep_10240ms",
              "Abs_RadioBuffer_TimeStep_20480ms",
              # "Abs_IdleTime_min",
              # "Abs_IdleTime_25.",
              # "Abs_IdleTime_50.",
              # "Abs_IdleTime_avg",
              # "Abs_IdleTime_75.",
              # "Abs_IdleTime_max",
              # "Abs_IdleTime_FirstMB",
              # "Abs_IdleTime_FirstSec",
              # "Abs_IdleTime_VolStep_30KB",
              # "Abs_IdleTime_VolStep_90KB",
              # "Abs_IdleTime_VolStep_240KB",
              # "Abs_IdleTime_VolStep_630KB",
              # "Abs_IdleTime_VolStep_1650KB",
              # "Abs_IdleTime_VolStep_4320KB",
              # "Abs_IdleTime_TimeStep_40ms",
              # "Abs_IdleTime_TimeStep_80ms",
              # "Abs_IdleTime_TimeStep_160ms",
              # "Abs_IdleTime_TimeStep_320ms",
              # "Abs_IdleTime_TimeStep_640ms",
              # "Abs_IdleTime_TimeStep_1280ms",
              # "Abs_IdleTime_TimeStep_2560ms",
              # "Abs_IdleTime_TimeStep_5120ms",
              # "Abs_IdleTime_TimeStep_10240ms",
              # "Abs_IdleTime_TimeStep_20480ms",
              "Abs_SegmentSizes_min",
              "Abs_SegmentSizes_25.",
              "Abs_SegmentSizes_50.",
              "Abs_SegmentSizes_avg",
              "Abs_SegmentSizes_75.",
              "Abs_SegmentSizes_max",
              "Abs_SegmentSizes_FirstMB",
              "Abs_SegmentSizes_FirstSec",
              "Abs_SegmentSizes_VolStep_30KB",
              "Abs_SegmentSizes_VolStep_90KB",
              "Abs_SegmentSizes_VolStep_240KB",
              "Abs_SegmentSizes_VolStep_630KB",
              "Abs_SegmentSizes_VolStep_1650KB",
              "Abs_SegmentSizes_VolStep_4320KB",
              "Abs_SegmentSizes_TimeStep_40ms",
              "Abs_SegmentSizes_TimeStep_80ms",
              "Abs_SegmentSizes_TimeStep_160ms",
              "Abs_SegmentSizes_TimeStep_320ms",
              "Abs_SegmentSizes_TimeStep_640ms",
              "Abs_SegmentSizes_TimeStep_1280ms",
              "Abs_SegmentSizes_TimeStep_2560ms",
              "Abs_SegmentSizes_TimeStep_5120ms",
              "Abs_SegmentSizes_TimeStep_10240ms",
              "Abs_SegmentSizes_TimeStep_20480ms",
              "Abs_PacketLost_sum",
              "Abs_PacketLost_FirstMB",
              "Abs_PacketLost_FirstSec",
              "Abs_PacketLost_VolStep_30KB",
              "Abs_PacketLost_VolStep_90KB",
              "Abs_PacketLost_VolStep_240KB",
              "Abs_PacketLost_VolStep_630KB",
              "Abs_PacketLost_VolStep_1650KB",
              "Abs_PacketLost_VolStep_4320KB",
              "Abs_PacketLost_TimeStep_40ms",
              "Abs_PacketLost_TimeStep_80ms",
              "Abs_PacketLost_TimeStep_160ms",
              "Abs_PacketLost_TimeStep_320ms",
              "Abs_PacketLost_TimeStep_640ms",
              "Abs_PacketLost_TimeStep_1280ms",
              "Abs_PacketLost_TimeStep_2560ms",
              "Abs_PacketLost_TimeStep_5120ms",
              "Abs_PacketLost_TimeStep_10240ms",
              "Abs_PacketLost_TimeStep_20480ms",
              "Abs_PushEvents_sum",
              "Abs_PushEvents_FirstMB",
              "Abs_PushEvents_FirstSec",
              "Abs_PushEvents_VolStep_30KB",
              "Abs_PushEvents_VolStep_90KB",
              "Abs_PushEvents_VolStep_240KB",
              "Abs_PushEvents_VolStep_630KB",
              "Abs_PushEvents_VolStep_1650KB",
              "Abs_PushEvents_VolStep_4320KB",
              "Abs_PushEvents_TimeStep_40ms",
              "Abs_PushEvents_TimeStep_80ms",
              "Abs_PushEvents_TimeStep_160ms",
              "Abs_PushEvents_TimeStep_320ms",
              "Abs_PushEvents_TimeStep_640ms",
              "Abs_PushEvents_TimeStep_1280ms",
              "Abs_PushEvents_TimeStep_2560ms",
              "Abs_PushEvents_TimeStep_5120ms",
              "Abs_PushEvents_TimeStep_10240ms",
              "Abs_PushEvents_TimeStep_20480ms",
              "Abs_BufferRatio_min",
              "Abs_BufferRatio_25.",
              "Abs_BufferRatio_50.",
              "Abs_BufferRatio_avg",
              "Abs_BufferRatio_75.",
              "Abs_BufferRatio_max",
              "Abs_BufferRatio_FirstMB",
              "Abs_BufferRatio_FirstSec",
              "Abs_BufferRatio_VolStep_30KB",
              "Abs_BufferRatio_VolStep_90KB",
              "Abs_BufferRatio_VolStep_240KB",
              "Abs_BufferRatio_VolStep_630KB",
              "Abs_BufferRatio_VolStep_1650KB",
              "Abs_BufferRatio_VolStep_4320KB",
              "Abs_BufferRatio_TimeStep_40ms",
              "Abs_BufferRatio_TimeStep_80ms",
              "Abs_BufferRatio_TimeStep_160ms",
              "Abs_BufferRatio_TimeStep_320ms",
              "Abs_BufferRatio_TimeStep_640ms",
              "Abs_BufferRatio_TimeStep_1280ms",
              "Abs_BufferRatio_TimeStep_2560ms",
              "Abs_BufferRatio_TimeStep_5120ms",
              "Abs_BufferRatio_TimeStep_10240ms",
              "Abs_BufferRatio_TimeStep_20480ms",
              "Abs_Burst_sum",
              "Abs_Burst_FirstMB",
              "Abs_Burst_FirstSec",
              "Abs_Burst_VolStep_30KB",
              "Abs_Burst_VolStep_90KB",
              "Abs_Burst_VolStep_240KB",
              "Abs_Burst_VolStep_630KB",
              "Abs_Burst_VolStep_1650KB",
              "Abs_Burst_VolStep_4320KB",
              "Abs_Burst_TimeStep_40ms",
              "Abs_Burst_TimeStep_80ms",
              "Abs_Burst_TimeStep_160ms",
              "Abs_Burst_TimeStep_320ms",
              "Abs_Burst_TimeStep_640ms",
              "Abs_Burst_TimeStep_1280ms",
              "Abs_Burst_TimeStep_2560ms",
              "Abs_Burst_TimeStep_5120ms",
              "Abs_Burst_TimeStep_10240ms",
              "Abs_Burst_TimeStep_20480ms",
              "Abs_BurstSizes_min",
              "Abs_BurstSizes_25.",
              "Abs_BurstSizes_50.",
              "Abs_BurstSizes_avg",
              "Abs_BurstSizes_75.",
              "Abs_BurstSizes_max",
              "Abs_BurstSizes_FirstMB",
              "Abs_BurstSizes_FirstSec",
              "Abs_BurstSizes_VolStep_30KB",
              "Abs_BurstSizes_VolStep_90KB",
              "Abs_BurstSizes_VolStep_240KB",
              "Abs_BurstSizes_VolStep_630KB",
              "Abs_BurstSizes_VolStep_1650KB",
              "Abs_BurstSizes_VolStep_4320KB",
              "Abs_BurstSizes_TimeStep_40ms",
              "Abs_BurstSizes_TimeStep_80ms",
              "Abs_BurstSizes_TimeStep_160ms",
              "Abs_BurstSizes_TimeStep_320ms",
              "Abs_BurstSizes_TimeStep_640ms",
              "Abs_BurstSizes_TimeStep_1280ms",
              "Abs_BurstSizes_TimeStep_2560ms",
              "Abs_BurstSizes_TimeStep_5120ms",
              "Abs_BurstSizes_TimeStep_10240ms",
              "Abs_BurstSizes_TimeStep_20480ms",
              "Abs_RTOEvents_sum",
              "Abs_RTOEvents_FirstMB",
              "Abs_RTOEvents_FirstSec",
              "Abs_RTOEvents_VolStep_30KB",
              "Abs_RTOEvents_VolStep_90KB",
              "Abs_RTOEvents_VolStep_240KB",
              "Abs_RTOEvents_VolStep_630KB",
              "Abs_RTOEvents_VolStep_1650KB",
              "Abs_RTOEvents_VolStep_4320KB",
              "Abs_RTOEvents_TimeStep_40ms",
              "Abs_RTOEvents_TimeStep_80ms",
              "Abs_RTOEvents_TimeStep_160ms",
              "Abs_RTOEvents_TimeStep_320ms",
              "Abs_RTOEvents_TimeStep_640ms",
              "Abs_RTOEvents_TimeStep_1280ms",
              "Abs_RTOEvents_TimeStep_2560ms",
              "Abs_RTOEvents_TimeStep_5120ms",
              "Abs_RTOEvents_TimeStep_10240ms",
              "Abs_RTOEvents_TimeStep_20480ms",
              "total_packets_b2a",
              "resets_sent_a2b",
              "resets_sent_b2a",
              "ack_pkts_sent_a2b",
              "pure_acks_sent_a2b",
              "sack_pkts_sent_a2b",
              "dsack_pkts_sent_a2b",
              "max_sack_blks.ack_a2b",
              "unique_bytes_sent_b2a",
              "actual_data_pkts_b2a",
              "actual_data_bytes_b2a",
              "rexmt_data_pkts_b2a",
              "rexmt_data_bytes_b2a",
              "zwnd_probe_pkts_b2a",
              "zwnd_probe_bytes_b2a",
              "outoforder_pkts_b2a",
              "pushed_data_pkts_b2a",
              "adv_wind_scale_a2b",
              "sacks_sent_a2b",
              "urgent_data_pkts_b2a",
              "urgent_data_bytes_b2a",
              "mss_requested_a2b",
              "mss_requested_b2a",
              "max_segm_size_b2a",
              "min_segm_size_b2a",
              "avg_segm_size_b2a",
              "max_win_adv_a2b",
              "min_win_adv_a2b",
              "zero_win_adv_a2b",
              "avg_win_adv_a2b",
              "initial_window_bytes_b2a",
              "initial_window_pkts_b2a",
              "ttl_stream_length_b2a",
              "missed_data_b2a",
              "truncated_data_b2a",
              "truncated_packets_b2a",
              # "idletime_max_a2b",
              # "idletime_max_b2a",
              "hardware_dups_a2b",
              "hardware_dups_b2a",
              "RTT_from_3WHS_a2b",
              "RTT_from_3WHS_b2a",
              "post.loss_acks_a2b",
              "ambiguous_acks_a2b",
              "segs_cum_acked_a2b",
              "duplicate_acks_a2b",
              "triple_dupacks_a2b",
              "max_._retrans_b2a",
              "min_retr_time_b2a",
              "max_retr_time_b2a",
              "avg_retr_time_b2a",
              "sdv_retr_time_b2a",
              "RelEst_PushEvents_VolStep_30KB",
              "RelEst_PushEvents_VolStep_90KB",
              "RelEst_PushEvents_VolStep_240KB",
              "RelEst_PushEvents_VolStep_630KB",
              "RelEst_PushEvents_VolStep_1650KB",
              "RelEst_PushEvents_VolStep_4320KB",
              "RelEst_PushEvents_TimeStep_40ms",
              "RelEst_PushEvents_TimeStep_80ms",
              "RelEst_PushEvents_TimeStep_160ms",
              "RelEst_PushEvents_TimeStep_320ms",
              "RelEst_PushEvents_TimeStep_640ms",
              "RelEst_PushEvents_TimeStep_1280ms",
              "RelEst_PushEvents_TimeStep_2560ms",
              "RelEst_PushEvents_TimeStep_5120ms",
              "RelEst_PushEvents_TimeStep_10240ms",
              "RelEst_PushEvents_TimeStep_20480ms",
              "Abs_RWIN_CWIN_TimeStep_40ms",
              "Abs_RWIN_CWIN_TimeStep_80ms",
              "Abs_RWIN_CWIN_TimeStep_160ms",
              "Abs_RWIN_CWIN_TimeStep_320ms",
              "Abs_RWIN_CWIN_TimeStep_640ms",
              "Abs_RWIN_CWIN_TimeStep_1280ms",
              "Abs_RWIN_CWIN_TimeStep_2560ms",
              "Abs_RWIN_CWIN_TimeStep_5120ms",
              "Abs_RWIN_CWIN_TimeStep_10240ms",
              "Abs_RWIN_CWIN_TimeStep_20480ms",
              "Abs_RWIN_CWIN_VolStep_30KB",
              "Abs_RWIN_CWIN_VolStep_90KB",
              "Abs_RWIN_CWIN_VolStep_240KB",
              "Abs_RWIN_CWIN_VolStep_630KB",
              "Abs_RWIN_CWIN_VolStep_1650KB",
              "Abs_RWIN_CWIN_VolStep_4320KB",
              "Abs_PacketLost_Acc_VolStep_30KB",
              "Abs_PacketLost_Acc_VolStep_90KB",
              "Abs_PacketLost_Acc_VolStep_240KB",
              "Abs_PacketLost_Acc_VolStep_630KB",
              "Abs_PacketLost_Acc_VolStep_1650KB",
              "Abs_PacketLost_Acc_VolStep_4320KB",
              "Abs_PacketLost_Acc_TimeStep_40ms",
              "Abs_PacketLost_Acc_TimeStep_80ms",
              "Abs_PacketLost_Acc_TimeStep_160ms",
              "Abs_PacketLost_Acc_TimeStep_320ms",
              "Abs_PacketLost_Acc_TimeStep_640ms",
              "Abs_PacketLost_Acc_TimeStep_1280ms",
              "Abs_PacketLost_Acc_TimeStep_2560ms",
              "Abs_PacketLost_Acc_TimeStep_5120ms",
              "Abs_PacketLost_Acc_TimeStep_10240ms",
              "Abs_PacketLost_Acc_TimeStep_20480ms"
             ]
             
             



attributes_throughput = ["Test.Throughput.kbit.s",
              "End.RSSI.dBm",
              "End.RSRP.dBm",
              "End.SINR.dB",
              "End.RSCP.dBm",
              "End.EcNo.dB",
              "Start.RSSI.dBm",
              "Start.RSRP.dBm",
              "Start.SINR.dB",
              "Start.RSCP.dBm",
              "Start.EcNo.dB",
              "Time.to.First.Byte.s",
              "Service.Access.RSSI.Start.dBm",
              "Service.Access.RSRP.Start.dBm",
              "Service.Access.SINR.Start.dB",
              "Service.Access.RSCP.Start.dBm",
              "Service.Access.EcNo.Start.dBm",
              #    "Carrier.Aggregation.SCC1.Usage.%",
              #    "Carrier.Aggregation.SCC2.Usage.%",
              #    "Carrier.Aggregation.SCC3.Usage.%",
              #    "Carrier.Aggregation.SCC4.Usage.%",
              #    "Carrier.Aggregation.SCC1.Usage.%.UL",
              #    "Carrier.Aggregation.SCC2.Usage.%.UL",
              "tcp.frame.time_relative.syn",
              "tcp.frame.time_relative.sck",
              "tcp.first.rtt",
              "tcp.frame.time_relative.ack",
              "tcp.3whs",
              "tcp.frame.time_relative.req",
              "tcp.idle",
              "tcp.frame.time_relative.res",
              "tcp.resp.time",
              "tcp.first.sec.num.ue.ip",
              "tcp.first.sec.num.ports",
              "tcp.first.sec.volume.ul",
              "tcp.first.sec.volume.dl",
              "transfer.frame.time_relative.FirstSec",
              "tcp.first.sec.num.server.ip",
              "tcp.resp_3whs_delta",
              "Abs_DownlinkDelay_min",
              "Abs_DownlinkDelay_25.",
              "Abs_DownlinkDelay_50.",
              "Abs_DownlinkDelay_avg",
              "Abs_DownlinkDelay_75.",
              "Abs_DownlinkDelay_max",
              "Abs_DownlinkDelay_FirstMB",
              "Abs_DownlinkDelay_FirstSec",
              "Abs_DownlinkDelay_VolStep_30KB",
              "Abs_DownlinkDelay_VolStep_90KB",
              "Abs_DownlinkDelay_VolStep_240KB",
              "Abs_DownlinkDelay_VolStep_630KB",
              "Abs_DownlinkDelay_VolStep_1650KB",
              "Abs_DownlinkDelay_VolStep_4320KB",
              "Abs_DownlinkDelay_TimeStep_40ms",
              "Abs_DownlinkDelay_TimeStep_80ms",
              "Abs_DownlinkDelay_TimeStep_160ms",
              "Abs_DownlinkDelay_TimeStep_320ms",
              "Abs_DownlinkDelay_TimeStep_640ms",
              "Abs_DownlinkDelay_TimeStep_1280ms",
              "Abs_DownlinkDelay_TimeStep_2560ms",
              "Abs_DownlinkDelay_TimeStep_5120ms",
              "Abs_DownlinkDelay_TimeStep_10240ms",
              "Abs_DownlinkDelay_TimeStep_20480ms",
              "Abs_UplinkDelay_min",
              "Abs_UplinkDelay_25.",
              "Abs_UplinkDelay_50.",
              "Abs_UplinkDelay_avg",
              "Abs_UplinkDelay_75.",
              "Abs_UplinkDelay_max",
              "Abs_UplinkDelay_FirstMB",
              "Abs_UplinkDelay_FirstSec",
              "Abs_UplinkDelay_VolStep_30KB",
              "Abs_UplinkDelay_VolStep_90KB",
              "Abs_UplinkDelay_VolStep_240KB",
              "Abs_UplinkDelay_VolStep_630KB",
              "Abs_UplinkDelay_VolStep_1650KB",
              "Abs_UplinkDelay_VolStep_4320KB",
              "Abs_UplinkDelay_TimeStep_40ms",
              "Abs_UplinkDelay_TimeStep_80ms",
              "Abs_UplinkDelay_TimeStep_160ms",
              "Abs_UplinkDelay_TimeStep_320ms",
              "Abs_UplinkDelay_TimeStep_640ms",
              "Abs_UplinkDelay_TimeStep_1280ms",
              "Abs_UplinkDelay_TimeStep_2560ms",
              "Abs_UplinkDelay_TimeStep_5120ms",
              "Abs_UplinkDelay_TimeStep_10240ms",
              "Abs_UplinkDelay_TimeStep_20480ms",
              # "Abs_DownlinkDeltaDelay_min",
              # "Abs_DownlinkDeltaDelay_25.",
              # "Abs_DownlinkDeltaDelay_50.",
              # "Abs_DownlinkDeltaDelay_avg",
              # "Abs_DownlinkDeltaDelay_75.",
              # "Abs_DownlinkDeltaDelay_max",
              # "Abs_DownlinkDeltaDelay_FirstMB",
              # "Abs_DownlinkDeltaDelay_FirstSec",
              # "Abs_DownlinkDeltaDelay_VolStep_30KB",
              # "Abs_DownlinkDeltaDelay_VolStep_90KB",
              # "Abs_DownlinkDeltaDelay_VolStep_240KB",
              # "Abs_DownlinkDeltaDelay_VolStep_630KB",
              # "Abs_DownlinkDeltaDelay_VolStep_1650KB",
              # "Abs_DownlinkDeltaDelay_VolStep_4320KB",
              # "Abs_DownlinkDeltaDelay_TimeStep_40ms",
              # "Abs_DownlinkDeltaDelay_TimeStep_80ms",
              # "Abs_DownlinkDeltaDelay_TimeStep_160ms",
              # "Abs_DownlinkDeltaDelay_TimeStep_320ms",
              # "Abs_DownlinkDeltaDelay_TimeStep_640ms",
              # "Abs_DownlinkDeltaDelay_TimeStep_1280ms",
              # "Abs_DownlinkDeltaDelay_TimeStep_2560ms",
              # "Abs_DownlinkDeltaDelay_TimeStep_5120ms",
              # "Abs_DownlinkDeltaDelay_TimeStep_10240ms",
              # "Abs_DownlinkDeltaDelay_TimeStep_20480ms",
              # "Abs_UplinkDeltaDelay_min",
              # "Abs_UplinkDeltaDelay_25.",
              # "Abs_UplinkDeltaDelay_50.",
              # "Abs_UplinkDeltaDelay_avg",
              # "Abs_UplinkDeltaDelay_75.",
              # "Abs_UplinkDeltaDelay_max",
              # "Abs_UplinkDeltaDelay_FirstMB",
              # "Abs_UplinkDeltaDelay_FirstSec",
              # "Abs_UplinkDeltaDelay_VolStep_30KB",
              # "Abs_UplinkDeltaDelay_VolStep_90KB",
              # "Abs_UplinkDeltaDelay_VolStep_240KB",
              # "Abs_UplinkDeltaDelay_VolStep_630KB",
              # "Abs_UplinkDeltaDelay_VolStep_1650KB",
              # "Abs_UplinkDeltaDelay_VolStep_4320KB",
              # "Abs_UplinkDeltaDelay_TimeStep_40ms",
              # "Abs_UplinkDeltaDelay_TimeStep_80ms",
              # "Abs_UplinkDeltaDelay_TimeStep_160ms",
              # "Abs_UplinkDeltaDelay_TimeStep_320ms",
              # "Abs_UplinkDeltaDelay_TimeStep_640ms",
              # "Abs_UplinkDeltaDelay_TimeStep_1280ms",
              # "Abs_UplinkDeltaDelay_TimeStep_2560ms",
              # "Abs_UplinkDeltaDelay_TimeStep_5120ms",
              # "Abs_UplinkDeltaDelay_TimeStep_10240ms",
              # "Abs_UplinkDeltaDelay_TimeStep_20480ms",
              "Abs_RTT_min",
              "Abs_RTT_25.",
              "Abs_RTT_50.",
              "Abs_RTT_avg",
              "Abs_RTT_75.",
              "Abs_RTT_max",
              "Abs_RTT_FirstMB",
              "Abs_RTT_FirstSec",
              "Abs_RTT_VolStep_30KB",
              "Abs_RTT_VolStep_90KB",
              "Abs_RTT_VolStep_240KB",
              "Abs_RTT_VolStep_630KB",
              "Abs_RTT_VolStep_1650KB",
              "Abs_RTT_VolStep_4320KB",
              "Abs_RTT_TimeStep_40ms",
              "Abs_RTT_TimeStep_80ms",
              "Abs_RTT_TimeStep_160ms",
              "Abs_RTT_TimeStep_320ms",
              "Abs_RTT_TimeStep_640ms",
              "Abs_RTT_TimeStep_1280ms",
              "Abs_RTT_TimeStep_2560ms",
              "Abs_RTT_TimeStep_5120ms",
              "Abs_RTT_TimeStep_10240ms",
              "Abs_RTT_TimeStep_20480ms",
              "Abs_CWIN_min",
              "Abs_CWIN_25.",
              "Abs_CWIN_50.",
              "Abs_CWIN_avg",
              "Abs_CWIN_75.",
              "Abs_CWIN_max",
              "Abs_CWIN_FirstMB",
              "Abs_CWIN_FirstSec",
              "Abs_CWIN_VolStep_30KB",
              "Abs_CWIN_VolStep_90KB",
              "Abs_CWIN_VolStep_240KB",
              "Abs_CWIN_VolStep_630KB",
              "Abs_CWIN_VolStep_1650KB",
              "Abs_CWIN_VolStep_4320KB",
              "Abs_CWIN_TimeStep_40ms",
              "Abs_CWIN_TimeStep_80ms",
              "Abs_CWIN_TimeStep_160ms",
              "Abs_CWIN_TimeStep_320ms",
              "Abs_CWIN_TimeStep_640ms",
              "Abs_CWIN_TimeStep_1280ms",
              "Abs_CWIN_TimeStep_2560ms",
              "Abs_CWIN_TimeStep_5120ms",
              "Abs_CWIN_TimeStep_10240ms",
              "Abs_CWIN_TimeStep_20480ms",
              "Abs_RWIN_min",
              "Abs_RWIN_25.",
              "Abs_RWIN_50.",
              "Abs_RWIN_avg",
              "Abs_RWIN_75.",
              "Abs_RWIN_max",
              "Abs_RWIN_FirstMB",
              "Abs_RWIN_FirstSec",
              "Abs_RWIN_VolStep_30KB",
              "Abs_RWIN_VolStep_90KB",
              "Abs_RWIN_VolStep_240KB",
              "Abs_RWIN_VolStep_630KB",
              "Abs_RWIN_VolStep_1650KB",
              "Abs_RWIN_VolStep_4320KB",
              "Abs_RWIN_TimeStep_40ms",
              "Abs_RWIN_TimeStep_80ms",
              "Abs_RWIN_TimeStep_160ms",
              "Abs_RWIN_TimeStep_320ms",
              "Abs_RWIN_TimeStep_640ms",
              "Abs_RWIN_TimeStep_1280ms",
              "Abs_RWIN_TimeStep_2560ms",
              "Abs_RWIN_TimeStep_5120ms",
              "Abs_RWIN_TimeStep_10240ms",
              "Abs_RWIN_TimeStep_20480ms",
              "Abs_WINRatio_min",
              "Abs_WINRatio_25.",
              "Abs_WINRatio_50.",
              "Abs_WINRatio_avg",
              "Abs_WINRatio_75.",
              "Abs_WINRatio_max",
              "Abs_WINRatio_FirstMB",
              "Abs_WINRatio_FirstSec",
              "Abs_WINRatio_VolStep_30KB",
              "Abs_WINRatio_VolStep_90KB",
              "Abs_WINRatio_VolStep_240KB",
              "Abs_WINRatio_VolStep_630KB",
              "Abs_WINRatio_VolStep_1650KB",
              "Abs_WINRatio_VolStep_4320KB",
              "Abs_WINRatio_TimeStep_40ms",
              "Abs_WINRatio_TimeStep_80ms",
              "Abs_WINRatio_TimeStep_160ms",
              "Abs_WINRatio_TimeStep_320ms",
              "Abs_WINRatio_TimeStep_640ms",
              "Abs_WINRatio_TimeStep_1280ms",
              "Abs_WINRatio_TimeStep_2560ms",
              "Abs_WINRatio_TimeStep_5120ms",
              "Abs_WINRatio_TimeStep_10240ms",
              "Abs_WINRatio_TimeStep_20480ms",
              "Abs_RadioBuffer_min",
              "Abs_RadioBuffer_25.",
              "Abs_RadioBuffer_50.",
              "Abs_RadioBuffer_avg",
              "Abs_RadioBuffer_75.",
              "Abs_RadioBuffer_max",
              "Abs_RadioBuffer_FirstMB",
              "Abs_RadioBuffer_FirstSec",
              "Abs_RadioBuffer_VolStep_30KB",
              "Abs_RadioBuffer_VolStep_90KB",
              "Abs_RadioBuffer_VolStep_240KB",
              "Abs_RadioBuffer_VolStep_630KB",
              "Abs_RadioBuffer_VolStep_1650KB",
              "Abs_RadioBuffer_VolStep_4320KB",
              "Abs_RadioBuffer_TimeStep_40ms",
              "Abs_RadioBuffer_TimeStep_80ms",
              "Abs_RadioBuffer_TimeStep_160ms",
              "Abs_RadioBuffer_TimeStep_320ms",
              "Abs_RadioBuffer_TimeStep_640ms",
              "Abs_RadioBuffer_TimeStep_1280ms",
              "Abs_RadioBuffer_TimeStep_2560ms",
              "Abs_RadioBuffer_TimeStep_5120ms",
              "Abs_RadioBuffer_TimeStep_10240ms",
              "Abs_RadioBuffer_TimeStep_20480ms",
              # "Abs_IdleTime_min",
              # "Abs_IdleTime_25.",
              # "Abs_IdleTime_50.",
              # "Abs_IdleTime_avg",
              # "Abs_IdleTime_75.",
              # "Abs_IdleTime_max",
              # "Abs_IdleTime_FirstMB",
              # "Abs_IdleTime_FirstSec",
              # "Abs_IdleTime_VolStep_30KB",
              # "Abs_IdleTime_VolStep_90KB",
              # "Abs_IdleTime_VolStep_240KB",
              # "Abs_IdleTime_VolStep_630KB",
              # "Abs_IdleTime_VolStep_1650KB",
              # "Abs_IdleTime_VolStep_4320KB",
              # "Abs_IdleTime_TimeStep_40ms",
              # "Abs_IdleTime_TimeStep_80ms",
              # "Abs_IdleTime_TimeStep_160ms",
              # "Abs_IdleTime_TimeStep_320ms",
              # "Abs_IdleTime_TimeStep_640ms",
              # "Abs_IdleTime_TimeStep_1280ms",
              # "Abs_IdleTime_TimeStep_2560ms",
              # "Abs_IdleTime_TimeStep_5120ms",
              # "Abs_IdleTime_TimeStep_10240ms",
              # "Abs_IdleTime_TimeStep_20480ms",
              "Abs_SegmentSizes_min",
              "Abs_SegmentSizes_25.",
              "Abs_SegmentSizes_50.",
              "Abs_SegmentSizes_avg",
              "Abs_SegmentSizes_75.",
              "Abs_SegmentSizes_max",
              "Abs_SegmentSizes_FirstMB",
              "Abs_SegmentSizes_FirstSec",
              "Abs_SegmentSizes_VolStep_30KB",
              "Abs_SegmentSizes_VolStep_90KB",
              "Abs_SegmentSizes_VolStep_240KB",
              "Abs_SegmentSizes_VolStep_630KB",
              "Abs_SegmentSizes_VolStep_1650KB",
              "Abs_SegmentSizes_VolStep_4320KB",
              "Abs_SegmentSizes_TimeStep_40ms",
              "Abs_SegmentSizes_TimeStep_80ms",
              "Abs_SegmentSizes_TimeStep_160ms",
              "Abs_SegmentSizes_TimeStep_320ms",
              "Abs_SegmentSizes_TimeStep_640ms",
              "Abs_SegmentSizes_TimeStep_1280ms",
              "Abs_SegmentSizes_TimeStep_2560ms",
              "Abs_SegmentSizes_TimeStep_5120ms",
              "Abs_SegmentSizes_TimeStep_10240ms",
              "Abs_SegmentSizes_TimeStep_20480ms",
              "Abs_PacketLost_sum",
              "Abs_PacketLost_FirstMB",
              "Abs_PacketLost_FirstSec",
              "Abs_PacketLost_VolStep_30KB",
              "Abs_PacketLost_VolStep_90KB",
              "Abs_PacketLost_VolStep_240KB",
              "Abs_PacketLost_VolStep_630KB",
              "Abs_PacketLost_VolStep_1650KB",
              "Abs_PacketLost_VolStep_4320KB",
              "Abs_PacketLost_TimeStep_40ms",
              "Abs_PacketLost_TimeStep_80ms",
              "Abs_PacketLost_TimeStep_160ms",
              "Abs_PacketLost_TimeStep_320ms",
              "Abs_PacketLost_TimeStep_640ms",
              "Abs_PacketLost_TimeStep_1280ms",
              "Abs_PacketLost_TimeStep_2560ms",
              "Abs_PacketLost_TimeStep_5120ms",
              "Abs_PacketLost_TimeStep_10240ms",
              "Abs_PacketLost_TimeStep_20480ms",
              "Abs_PushEvents_sum",
              "Abs_PushEvents_FirstMB",
              "Abs_PushEvents_FirstSec",
              "Abs_PushEvents_VolStep_30KB",
              "Abs_PushEvents_VolStep_90KB",
              "Abs_PushEvents_VolStep_240KB",
              "Abs_PushEvents_VolStep_630KB",
              "Abs_PushEvents_VolStep_1650KB",
              "Abs_PushEvents_VolStep_4320KB",
              "Abs_PushEvents_TimeStep_40ms",
              "Abs_PushEvents_TimeStep_80ms",
              "Abs_PushEvents_TimeStep_160ms",
              "Abs_PushEvents_TimeStep_320ms",
              "Abs_PushEvents_TimeStep_640ms",
              "Abs_PushEvents_TimeStep_1280ms",
              "Abs_PushEvents_TimeStep_2560ms",
              "Abs_PushEvents_TimeStep_5120ms",
              "Abs_PushEvents_TimeStep_10240ms",
              "Abs_PushEvents_TimeStep_20480ms",
              "Abs_BufferRatio_min",
              "Abs_BufferRatio_25.",
              "Abs_BufferRatio_50.",
              "Abs_BufferRatio_avg",
              "Abs_BufferRatio_75.",
              "Abs_BufferRatio_max",
              "Abs_BufferRatio_FirstMB",
              "Abs_BufferRatio_FirstSec",
              "Abs_BufferRatio_VolStep_30KB",
              "Abs_BufferRatio_VolStep_90KB",
              "Abs_BufferRatio_VolStep_240KB",
              "Abs_BufferRatio_VolStep_630KB",
              "Abs_BufferRatio_VolStep_1650KB",
              "Abs_BufferRatio_VolStep_4320KB",
              "Abs_BufferRatio_TimeStep_40ms",
              "Abs_BufferRatio_TimeStep_80ms",
              "Abs_BufferRatio_TimeStep_160ms",
              "Abs_BufferRatio_TimeStep_320ms",
              "Abs_BufferRatio_TimeStep_640ms",
              "Abs_BufferRatio_TimeStep_1280ms",
              "Abs_BufferRatio_TimeStep_2560ms",
              "Abs_BufferRatio_TimeStep_5120ms",
              "Abs_BufferRatio_TimeStep_10240ms",
              "Abs_BufferRatio_TimeStep_20480ms",
              "Abs_Burst_sum",
              "Abs_Burst_FirstMB",
              "Abs_Burst_FirstSec",
              "Abs_Burst_VolStep_30KB",
              "Abs_Burst_VolStep_90KB",
              "Abs_Burst_VolStep_240KB",
              "Abs_Burst_VolStep_630KB",
              "Abs_Burst_VolStep_1650KB",
              "Abs_Burst_VolStep_4320KB",
              "Abs_Burst_TimeStep_40ms",
              "Abs_Burst_TimeStep_80ms",
              "Abs_Burst_TimeStep_160ms",
              "Abs_Burst_TimeStep_320ms",
              "Abs_Burst_TimeStep_640ms",
              "Abs_Burst_TimeStep_1280ms",
              "Abs_Burst_TimeStep_2560ms",
              "Abs_Burst_TimeStep_5120ms",
              "Abs_Burst_TimeStep_10240ms",
              "Abs_Burst_TimeStep_20480ms",
              "Abs_BurstSizes_min",
              "Abs_BurstSizes_25.",
              "Abs_BurstSizes_50.",
              "Abs_BurstSizes_avg",
              "Abs_BurstSizes_75.",
              "Abs_BurstSizes_max",
              "Abs_BurstSizes_FirstMB",
              "Abs_BurstSizes_FirstSec",
              "Abs_BurstSizes_VolStep_30KB",
              "Abs_BurstSizes_VolStep_90KB",
              "Abs_BurstSizes_VolStep_240KB",
              "Abs_BurstSizes_VolStep_630KB",
              "Abs_BurstSizes_VolStep_1650KB",
              "Abs_BurstSizes_VolStep_4320KB",
              "Abs_BurstSizes_TimeStep_40ms",
              "Abs_BurstSizes_TimeStep_80ms",
              "Abs_BurstSizes_TimeStep_160ms",
              "Abs_BurstSizes_TimeStep_320ms",
              "Abs_BurstSizes_TimeStep_640ms",
              "Abs_BurstSizes_TimeStep_1280ms",
              "Abs_BurstSizes_TimeStep_2560ms",
              "Abs_BurstSizes_TimeStep_5120ms",
              "Abs_BurstSizes_TimeStep_10240ms",
              "Abs_BurstSizes_TimeStep_20480ms",
              "Abs_RTOEvents_sum",
              "Abs_RTOEvents_FirstMB",
              "Abs_RTOEvents_FirstSec",
              "Abs_RTOEvents_VolStep_30KB",
              "Abs_RTOEvents_VolStep_90KB",
              "Abs_RTOEvents_VolStep_240KB",
              "Abs_RTOEvents_VolStep_630KB",
              "Abs_RTOEvents_VolStep_1650KB",
              "Abs_RTOEvents_VolStep_4320KB",
              "Abs_RTOEvents_TimeStep_40ms",
              "Abs_RTOEvents_TimeStep_80ms",
              "Abs_RTOEvents_TimeStep_160ms",
              "Abs_RTOEvents_TimeStep_320ms",
              "Abs_RTOEvents_TimeStep_640ms",
              "Abs_RTOEvents_TimeStep_1280ms",
              "Abs_RTOEvents_TimeStep_2560ms",
              "Abs_RTOEvents_TimeStep_5120ms",
              "Abs_RTOEvents_TimeStep_10240ms",
              "Abs_RTOEvents_TimeStep_20480ms",
              "total_packets_b2a",
              "resets_sent_a2b",
              "resets_sent_b2a",
              "ack_pkts_sent_a2b",
              "pure_acks_sent_a2b",
              "sack_pkts_sent_a2b",
              "dsack_pkts_sent_a2b",
              "max_sack_blks.ack_a2b",
              "unique_bytes_sent_b2a",
              "actual_data_pkts_b2a",
              "actual_data_bytes_b2a",
              "rexmt_data_pkts_b2a",
              "rexmt_data_bytes_b2a",
              "zwnd_probe_pkts_b2a",
              "zwnd_probe_bytes_b2a",
              "outoforder_pkts_b2a",
              "pushed_data_pkts_b2a",
              "adv_wind_scale_a2b",
              "sacks_sent_a2b",
              "urgent_data_pkts_b2a",
              "urgent_data_bytes_b2a",
              "mss_requested_a2b",
              "mss_requested_b2a",
              "max_segm_size_b2a",
              "min_segm_size_b2a",
              "avg_segm_size_b2a",
              "max_win_adv_a2b",
              "min_win_adv_a2b",
              "zero_win_adv_a2b",
              "avg_win_adv_a2b",
              "initial_window_bytes_b2a",
              "initial_window_pkts_b2a",
              "ttl_stream_length_b2a",
              "missed_data_b2a",
              "truncated_data_b2a",
              "truncated_packets_b2a",
              # "idletime_max_a2b",
              # "idletime_max_b2a",
              "hardware_dups_a2b",
              "hardware_dups_b2a",
              "RTT_from_3WHS_a2b",
              "RTT_from_3WHS_b2a",
              "post.loss_acks_a2b",
              "ambiguous_acks_a2b",
              "segs_cum_acked_a2b",
              "duplicate_acks_a2b",
              "triple_dupacks_a2b",
              "max_._retrans_b2a",
              "min_retr_time_b2a",
              "max_retr_time_b2a",
              "avg_retr_time_b2a",
              "sdv_retr_time_b2a",
              "RelEst_PushEvents_VolStep_30KB",
              "RelEst_PushEvents_VolStep_90KB",
              "RelEst_PushEvents_VolStep_240KB",
              "RelEst_PushEvents_VolStep_630KB",
              "RelEst_PushEvents_VolStep_1650KB",
              "RelEst_PushEvents_VolStep_4320KB",
              "RelEst_PushEvents_TimeStep_40ms",
              "RelEst_PushEvents_TimeStep_80ms",
              "RelEst_PushEvents_TimeStep_160ms",
              "RelEst_PushEvents_TimeStep_320ms",
              "RelEst_PushEvents_TimeStep_640ms",
              "RelEst_PushEvents_TimeStep_1280ms",
              "RelEst_PushEvents_TimeStep_2560ms",
              "RelEst_PushEvents_TimeStep_5120ms",
              "RelEst_PushEvents_TimeStep_10240ms",
              "RelEst_PushEvents_TimeStep_20480ms",
              "Abs_RWIN_CWIN_TimeStep_40ms",
              "Abs_RWIN_CWIN_TimeStep_80ms",
              "Abs_RWIN_CWIN_TimeStep_160ms",
              "Abs_RWIN_CWIN_TimeStep_320ms",
              "Abs_RWIN_CWIN_TimeStep_640ms",
              "Abs_RWIN_CWIN_TimeStep_1280ms",
              "Abs_RWIN_CWIN_TimeStep_2560ms",
              "Abs_RWIN_CWIN_TimeStep_5120ms",
              "Abs_RWIN_CWIN_TimeStep_10240ms",
              "Abs_RWIN_CWIN_TimeStep_20480ms",
              "Abs_RWIN_CWIN_VolStep_30KB",
              "Abs_RWIN_CWIN_VolStep_90KB",
              "Abs_RWIN_CWIN_VolStep_240KB",
              "Abs_RWIN_CWIN_VolStep_630KB",
              "Abs_RWIN_CWIN_VolStep_1650KB",
              "Abs_RWIN_CWIN_VolStep_4320KB",
              "Abs_PacketLost_Acc_VolStep_30KB",
              "Abs_PacketLost_Acc_VolStep_90KB",
              "Abs_PacketLost_Acc_VolStep_240KB",
              "Abs_PacketLost_Acc_VolStep_630KB",
              "Abs_PacketLost_Acc_VolStep_1650KB",
              "Abs_PacketLost_Acc_VolStep_4320KB",
              "Abs_PacketLost_Acc_TimeStep_40ms",
              "Abs_PacketLost_Acc_TimeStep_80ms",
              "Abs_PacketLost_Acc_TimeStep_160ms",
              "Abs_PacketLost_Acc_TimeStep_320ms",
              "Abs_PacketLost_Acc_TimeStep_640ms",
              "Abs_PacketLost_Acc_TimeStep_1280ms",
              "Abs_PacketLost_Acc_TimeStep_2560ms",
              "Abs_PacketLost_Acc_TimeStep_5120ms",
              "Abs_PacketLost_Acc_TimeStep_10240ms",
              "Abs_PacketLost_Acc_TimeStep_20480ms"
             ]
